# Generated by Django 5.1.4 on 2025-01-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=100)),
                ('end_location', models.CharField(max_length=100)),
                ('distance', models.FloatField()),
                ('duration', models.FloatField()),
                ('bus_number', models.CharField(max_length=10)),
                ('bus_stops', models.TextField()),
            ],
        ),
    ]
